/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TOYOSI
 */
public class Loan_app2 extends javax.swing.JFrame {

    /**
     * Creates new form Loan_app2
     */
    public Loan_app2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loanDurationTxt = new javax.swing.JTextField();
        calculateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        total = new javax.swing.JLabel();
        totalRepaymentTxt = new javax.swing.JTextField();
        interest = new javax.swing.JLabel();
        totalInterestTxt = new javax.swing.JTextField();
        loanAmountTxt = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ENTER LOAN AMOUNT");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel2.setText("LOAN APPLICATION");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ENTER DURATION");

        loanDurationTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loanDurationTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loanDurationTxtKeyTyped(evt);
            }
        });

        calculateBtn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        calculateBtn.setText("CALCULATE");
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });

        table.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MONTH", "AMOUNT", "INTEREST", "MONTHLY REPAYMENT"
            }
        ));
        jScrollPane1.setViewportView(table);

        total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        total.setText("TOTAL REPAYMENT");

        totalRepaymentTxt.setEditable(false);
        totalRepaymentTxt.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        totalRepaymentTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalRepaymentTxtActionPerformed(evt);
            }
        });

        interest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        interest.setText("TOTAL INTEREST");

        totalInterestTxt.setEditable(false);
        totalInterestTxt.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        totalInterestTxt.setText(" ");
        totalInterestTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalInterestTxtActionPerformed(evt);
            }
        });

        loanAmountTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loanAmountTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loanAmountTxtKeyTyped(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(153, 0, 0));
        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(242, 242, 242));
        clearBtn.setText("CLEAR");
        clearBtn.setBorder(null);
        clearBtn.setPreferredSize(new java.awt.Dimension(70, 50));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(loanAmountTxt)
                                .addGap(67, 67, 67)
                                .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(loanDurationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalRepaymentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(interest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalInterestTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanDurationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total)
                    .addComponent(totalInterestTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interest)
                    .addComponent(totalRepaymentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
        try {
            if (loanAmountTxt.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter loan amount");
                loanAmountTxt.requestFocus();
                return;
            }
            if (loanDurationTxt.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter loan duration");
                loanDurationTxt.requestFocus();
                return;
            }
  
            double loanAmount = Double.parseDouble(loanAmountTxt.getText());
            double duration = Double.parseDouble(loanDurationTxt.getText());

            double monthlyAmount = loanAmount / duration;

            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);

            double totalInterest = 0;
            double totalRepayment = 0;
            double remainingAmount = loanAmount;

            for (int month = 1; month <= duration; month++) {
                
                double interest = remainingAmount * 1.5/100;
                double repayment = monthlyAmount + interest;
                
                totalInterest += interest;
                totalRepayment += repayment;

                model.addRow(new Object[]{
                    month,
                    String.format("%.2f", monthlyAmount),
                     String.format("%.2f", interest),
                    String.format("%.2f", repayment)
                });
                remainingAmount -= monthlyAmount;
            }
            totalInterestTxt.setText(String.format("%.2f", totalInterest));
            totalRepaymentTxt.setText(String.format("%.2f", totalRepayment));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please enter valid numbers!",
                    "Error!",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_calculateBtnActionPerformed

    private void totalInterestTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalInterestTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalInterestTxtActionPerformed

    private void totalRepaymentTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalRepaymentTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalRepaymentTxtActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        loanAmountTxt.setText("");
        loanDurationTxt.setText("");

        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);

        totalRepaymentTxt.setText("");
        totalInterestTxt.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void loanAmountTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loanAmountTxtKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != 8 && c != 127) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Invalid Format! Only digits are allowed");

    }//GEN-LAST:event_loanAmountTxtKeyTyped
    }


    private void loanDurationTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loanDurationTxtKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != 8 && c != 127) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Invalid Format! Only digits are allowed");
    }//GEN-LAST:event_loanDurationTxtKeyTyped
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loan_app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loan_app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loan_app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loan_app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Loan_app2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel interest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loanAmountTxt;
    private javax.swing.JTextField loanDurationTxt;
    private javax.swing.JTable table;
    private javax.swing.JLabel total;
    private javax.swing.JTextField totalInterestTxt;
    private javax.swing.JTextField totalRepaymentTxt;
    // End of variables declaration//GEN-END:variables
}
