/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.Period;
/**
 *
 * @author TOYOSI
 */
public class Age_Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Age_Calculator
     */
    public Age_Calculator() {
        initComponents(); 
        todayDate.setText("TODAY'S DATE:"+java.time.LocalDate.now());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Age_Calculator = new javax.swing.JPanel();
        todayDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        todayDateLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dayOfBirth = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        yearOfBirth = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        monthOfBirth = new javax.swing.JTextField();
        calculateBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        yearsTxt = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        daysTxt = new javax.swing.JTextField();
        monthsTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Age_Calculator.setPreferredSize(new java.awt.Dimension(800, 500));

        todayDate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        todayDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        todayDate.setText("TODAY'S DATE:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("    AGE CALCULATOR");
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 35));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        todayDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        todayDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("ENTER BIRTHDAY");
        jLabel12.setPreferredSize(new java.awt.Dimension(180, 30));

        dayOfBirth.setText(" ");
        dayOfBirth.setPreferredSize(new java.awt.Dimension(250, 40));
        dayOfBirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dayOfBirthKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("ENTER BIRTHYEAR");
        jLabel13.setPreferredSize(new java.awt.Dimension(180, 30));

        yearOfBirth.setText(" ");
        yearOfBirth.setPreferredSize(new java.awt.Dimension(250, 40));
        yearOfBirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearOfBirthKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("ENTER BIRTHMONTH");
        jLabel14.setPreferredSize(new java.awt.Dimension(180, 30));

        monthOfBirth.setText(" ");
        monthOfBirth.setPreferredSize(new java.awt.Dimension(250, 40));
        monthOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthOfBirthActionPerformed(evt);
            }
        });
        monthOfBirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                monthOfBirthKeyTyped(evt);
            }
        });

        calculateBtn.setBackground(new java.awt.Color(153, 153, 153));
        calculateBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        calculateBtn.setForeground(new java.awt.Color(242, 242, 242));
        calculateBtn.setText("CALCULATE AGE");
        calculateBtn.setBorder(null);
        calculateBtn.setPreferredSize(new java.awt.Dimension(250, 40));
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("YOUR BIRTHDAY IS :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("YEARS");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("MONTHS");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("DAYS");

        yearsTxt.setEditable(false);
        yearsTxt.setText(" ");
        yearsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearsTxtActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(153, 0, 0));
        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(242, 242, 242));
        clearBtn.setText("CLEAR");
        clearBtn.setBorder(null);
        clearBtn.setPreferredSize(new java.awt.Dimension(70, 50));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        daysTxt.setEditable(false);
        daysTxt.setText(" ");
        daysTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysTxtActionPerformed(evt);
            }
        });

        monthsTxt.setEditable(false);
        monthsTxt.setText(" ");
        monthsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthsTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Age_CalculatorLayout = new javax.swing.GroupLayout(Age_Calculator);
        Age_Calculator.setLayout(Age_CalculatorLayout);
        Age_CalculatorLayout.setHorizontalGroup(
            Age_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Age_CalculatorLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(Age_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Age_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthOfBirth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Age_CalculatorLayout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monthsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(daysTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(Age_CalculatorLayout.createSequentialGroup()
                .addGroup(Age_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Age_CalculatorLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Age_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Age_CalculatorLayout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(todayDateLabel))))
                    .addComponent(todayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Age_CalculatorLayout.setVerticalGroup(
            Age_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Age_CalculatorLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(todayDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Age_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Age_CalculatorLayout.createSequentialGroup()
                        .addGroup(Age_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(todayDateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(Age_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(Age_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dayOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(Age_CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(yearsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(daysTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Age_Calculator, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Age_Calculator, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        dayOfBirth.setText("");
        monthOfBirth.setText("");
        yearOfBirth.setText("");
        yearsTxt.setText("");
        monthsTxt.setText("");
        daysTxt.setText("");

    }//GEN-LAST:event_clearBtnActionPerformed

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
        // TODO add your handling code here:
        try{
            if(dayOfBirth.getText().trim().isEmpty()){
              JOptionPane.showMessageDialog(this,"Enter birthday");
              dayOfBirth.requestFocus();
              return;
            }
            if(monthOfBirth.getText().trim().isEmpty()){
              JOptionPane.showMessageDialog(this,"Enter birthmonth");
              monthOfBirth.requestFocus();
              return;
            }
            if(yearOfBirth.getText().trim().isEmpty()){
              JOptionPane.showMessageDialog(this,"Enter birth year");
              yearOfBirth.requestFocus();
              return;
            }
            java.time.LocalDate today = java.time.LocalDate.now();
            todayDateLabel.setText(today.toString());
            int currentYear = today.getYear();

            int birthDay = Integer.parseInt(dayOfBirth.getText().trim());
            int birthMonth = Integer.parseInt(monthOfBirth.getText().trim());
            int birthYear = Integer.parseInt(yearOfBirth.getText().trim());

            if (birthYear > currentYear || birthYear <1){
                javax.swing.JOptionPane.showMessageDialog(this,"Error: Please enter a valid birth year!","Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (birthMonth < 1 || birthMonth >12){
                javax.swing.JOptionPane.showMessageDialog(this,"Error: Month must be between 1 and 12!","Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (birthDay < 1 || birthDay >31){
                javax.swing.JOptionPane.showMessageDialog(this,"Error: Day must be between 1 and 31!","Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            LocalDate birthDate = LocalDate.of(birthYear,birthMonth, birthDay);
            if(birthDate.isAfter(today)){
                JOptionPane.showMessageDialog(this,"Birth date cannot be in the future");
            }
            Period age = Period.between(birthDate,today);
            
            yearsTxt.setText(""+age.getYears());
            monthsTxt.setText(""+age.getMonths());
            daysTxt.setText(""+ age.getDays());
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                null,
                "Please enter valid numbers!",
                "Error!",
                JOptionPane.ERROR_MESSAGE
                
            );
        }catch(java.time.DateTimeException e){
            JOptionPane.showMessageDialog(this,"Invalid date");
            
            
        }

    }//GEN-LAST:event_calculateBtnActionPerformed

    private void yearsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearsTxtActionPerformed

    private void daysTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daysTxtActionPerformed

    private void monthsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthsTxtActionPerformed

    private void dayOfBirthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dayOfBirthKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
       if(!Character.isDigit(c)&&c!=8&&c!=127){
          evt.consume();
      JOptionPane.showMessageDialog(this,"Invalid Format");
}
    }//GEN-LAST:event_dayOfBirthKeyTyped

    private void monthOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthOfBirthActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_monthOfBirthActionPerformed

    private void monthOfBirthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthOfBirthKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
         if(!Character.isDigit(c)&&c!=8&&c!=127){
          evt.consume();
      JOptionPane.showMessageDialog(this,"Invalid Format");
}
    }//GEN-LAST:event_monthOfBirthKeyTyped

    private void yearOfBirthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearOfBirthKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
         if(yearOfBirth.getText().length()>=4&&c!=8&&c!=127){
          evt.consume();
          JOptionPane.showMessageDialog(this,"Year must be 4 digits");
          return;
         } 
         if(!Character.isDigit(c)&&c!=8&&c!=127){
             evt.consume();
             JOptionPane.showMessageDialog(this,"Invalid Format");
         }
    }//GEN-LAST:event_yearOfBirthKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Age_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Age_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Age_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Age_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Age_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Age_Calculator;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField dayOfBirth;
    private javax.swing.JTextField daysTxt;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField monthOfBirth;
    private javax.swing.JTextField monthsTxt;
    private javax.swing.JLabel todayDate;
    private javax.swing.JLabel todayDateLabel;
    private javax.swing.JTextField yearOfBirth;
    private javax.swing.JTextField yearsTxt;
    // End of variables declaration//GEN-END:variables
}
